# Generated by Django 4.1.3 on 2023-07-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimmeapi', '0002_remove_product_category_id_product_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default=1, max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(default=1, max_length=1000),
        ),
    ]
