# Generated by Django 4.1.3 on 2023-07-18 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimmeapi', '0004_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
